export type Language = "en" | "ar";

export const profileImageUrl = "https://i.ibb.co/Z1vvQmQ0/2.webp";
export const whatsappUrl = "https://wa.me/201004658868";

export const navigation = {
  en: [
    ["Home", "/"],
    ["Services", "/services"],
    ["Who I Help", "/who-we-help"],
    ["Case Studies", "/case-studies"],
    ["About", "/about"],
    ["Contact", "/contact"],
  ],
  ar: [
    ["الرئيسية", "/"],
    ["الخدمات", "/services"],
    ["مين أقدر أساعد", "/who-we-help"],
    ["سابقة الأعمال", "/case-studies"],
    ["عن Habiba Dapour", "/about"],
    ["تواصل معايا", "/contact"],
  ],
} as const;

export const services = {
  en: [
    {
      id: "management",
      title: "Social Media Management",
      preview: "From planning and publishing to account monitoring and performance analysis, I manage your social media through a strategy connected to your business goals.",
      problem: "The account is active, but daily decisions are disconnected and difficult to sustain.",
      fit: "Businesses that need consistent ownership aligned with wider priorities.",
      covers: ["Planning and publishing", "Account monitoring", "Community direction", "Performance reviews"],
      outcome: "A clearer, more consistent management system connected to the business.",
      cta: "Discuss Account Management",
    },
    {
      id: "strategy",
      title: "Content Strategy",
      preview: "I turn your business goals and ideas into a clear content direction that defines the audience, messaging, content pillars, and the role of each piece in the customer journey.",
      problem: "Content feels random, repetitive, or disconnected from the audience and customer journey.",
      fit: "Brands with ideas and expertise that need a structured direction before producing more content.",
      covers: ["Audience and positioning", "Messaging", "Content pillars", "Customer-journey roles"],
      outcome: "A purposeful content direction that guides decisions and production.",
      cta: "Build Your Content Direction",
    },
    {
      id: "audit",
      title: "Social Media Audit",
      preview: "I review your accounts, content, and performance to identify weaknesses, opportunities, and the most important actions for improvement.",
      problem: "You can see activity and data, but the causes of weak performance are still unclear.",
      fit: "Businesses that need an informed starting point before changing strategy or management.",
      covers: ["Profile and positioning", "Content direction", "Performance indicators", "Improvement priorities"],
      outcome: "A clearer view of the current situation and the most relevant next actions.",
      cta: "Request an Account Audit",
    },
    {
      id: "paid-media",
      title: "Paid Media Management",
      preview: "I plan and manage paid campaigns to reach qualified prospects and measure the outcomes that genuinely matter to the business.",
      problem: "Campaign activity is not supported by a clear target, creative direction, journey, or measurement plan.",
      fit: "Businesses ready to connect paid reach with a clear offer, audience, and conversion path.",
      covers: ["Campaign planning", "Audience direction", "Creative coordination", "Performance optimization"],
      outcome: "More informed paid-media decisions focused on qualified business actions.",
      cta: "Discuss Paid Media",
    },
  ],
  ar: [
    {
      id: "management",
      title: "إدارة حسابات السوشيال ميديا",
      preview: "من التخطيط والنشر إلى المتابعة وتحليل الأداء، بدير حساباتك وفق استراتيجية واضحة مرتبطة بأهداف البيزنس.",
      problem: "الحساب شغال، لكن القرارات اليومية منفصلة وصعب تستمر بنفس الجودة.",
      fit: "البيزنس اللي محتاج إدارة مستمرة وقرارات مرتبطة بالأولويات الأكبر.",
      covers: ["التخطيط والنشر", "متابعة الحساب", "توجيه المجتمع", "مراجعة الأداء"],
      outcome: "نظام إدارة أوضح وأكثر استمرارية وارتباطًا بالبيزنس.",
      cta: "ناقش إدارة حسابك",
    },
    {
      id: "strategy",
      title: "استراتيجية المحتوى",
      preview: "بحوّل أهداف البيزنس وأفكاره إلى اتجاه محتوى واضح يحدد الرسائل، الجمهور، أعمدة المحتوى ودور كل قطعة في رحلة العميل.",
      problem: "المحتوى عشوائي أو متكرر أو بعيد عن الجمهور ورحلة العميل.",
      fit: "البراندات اللي عندها أفكار وخبرة لكنها محتاجة اتجاه منظم قبل إنتاج محتوى أكتر.",
      covers: ["الجمهور وتحديد المكانة", "الرسائل", "أعمدة المحتوى", "دور المحتوى في رحلة العميل"],
      outcome: "اتجاه محتوى هادف يوجّه القرارات والإنتاج.",
      cta: "ابنِ اتجاه المحتوى",
    },
    {
      id: "audit",
      title: "تحليل حسابات السوشيال ميديا",
      preview: "براجع حساباتك والمحتوى والأداء علشان أحدد نقاط الضعف والفرص وأهم الخطوات المطلوبة للتحسين.",
      problem: "شايف النشاط والبيانات، لكن أسباب ضعف الأداء لسه مش واضحة.",
      fit: "البيزنس اللي محتاج نقطة بداية مدروسة قبل تغيير الاستراتيجية أو الإدارة.",
      covers: ["الملف التعريفي والمكانة", "اتجاه المحتوى", "مؤشرات الأداء", "أولويات التحسين"],
      outcome: "رؤية أوضح للوضع الحالي والخطوات التالية الأكثر صلة.",
      cta: "اطلب تحليل حسابك",
    },
    {
      id: "paid-media",
      title: "إدارة الإعلانات المدفوعة",
      preview: "بخطط وبدير الحملات الإعلانية بهدف الوصول لعملاء محتملين مؤهلين وقياس النتائج اللي تهم البيزنس فعلًا.",
      problem: "نشاط الحملات مش مدعوم بهدف أو كرياتيف أو رحلة أو طريقة قياس واضحة.",
      fit: "البيزنس الجاهز يربط الوصول المدفوع بعرض وجمهور ومسار تحويل واضح.",
      covers: ["تخطيط الحملات", "توجيه الجمهور", "تنسيق الكرياتيف", "تحسين الأداء"],
      outcome: "قرارات إعلانية أذكى تركز على الإجراءات المؤهلة للبيزنس.",
      cta: "ناقش الإعلانات المدفوعة",
    },
  ],
} as const;

export const audiences = {
  en: [
    {
      title: "Growing Businesses & Founders",
      copy: "If you run an established business but social media is not producing a clear impact—or you are still managing everything yourself—I can build a clearer system for content, management, and performance.",
      challenges: "Limited time, scattered decisions, and unclear business impact.",
      relevant: "Management, content strategy, and account audit.",
      improve: "Consistency, decision-making, and focus across the account.",
    },
    {
      title: "E-commerce Brands",
      copy: "If your ads generate traffic but conversions remain weak, I review the content, creative, customer journey, and performance instead of assuming the problem is only the advertising.",
      challenges: "Traffic without enough action and a fragmented customer journey.",
      relevant: "Content strategy, paid media, and performance audit.",
      improve: "Alignment between message, creative, journey, and measurement.",
    },
    {
      title: "Personal Brands & Experts",
      copy: "If you have strong expertise but your account does not communicate it clearly, I help turn that expertise into structured content that builds trust, authority, and action.",
      challenges: "Valuable expertise without a clear or consistent content structure.",
      relevant: "Positioning, content strategy, and account management.",
      improve: "Clarity, trust, and a stronger path from expertise to action.",
    },
    {
      title: "Local Businesses",
      copy: "If your business depends on nearby customers, I build a content direction that helps people discover the brand, engage with it, and understand its value.",
      challenges: "Low local awareness and an unclear reason to choose the brand.",
      relevant: "Content strategy, management, and paid media.",
      improve: "Local discovery, brand understanding, and meaningful engagement.",
    },
  ],
  ar: [
    {
      title: "البيزنس المتنامي والمؤسسون",
      copy: "لو عندك بيزنس قائم لكن السوشيال ميديا مش بتجيب نتيجة واضحة، أو بتدير الحساب بنفسك ومش لاقي وقت، بساعدك أبني نظام أوضح لإدارة المحتوى والأداء.",
      challenges: "وقت محدود وقرارات مشتتة وتأثير غير واضح على البيزنس.",
      relevant: "الإدارة واستراتيجية المحتوى وتحليل الحساب.",
      improve: "الاستمرارية وجودة القرار والتركيز داخل الحساب.",
    },
    {
      title: "براندات التجارة الإلكترونية",
      copy: "لو الإعلانات بتجيب زيارات لكن التحويلات ضعيفة، براجع المحتوى والكرياتيف ورحلة العميل والأداء بدل ما أفترض إن المشكلة في الإعلان وحده.",
      challenges: "زيارات بدون إجراء كافٍ ورحلة عميل غير مترابطة.",
      relevant: "استراتيجية المحتوى والإعلانات المدفوعة وتحليل الأداء.",
      improve: "الترابط بين الرسالة والكرياتيف والرحلة والقياس.",
    },
    {
      title: "البراندات الشخصية والخبراء",
      copy: "لو عندك خبرة قوية لكن حسابك مش بيعكسها، بساعدك تحول خبرتك إلى محتوى منظم يبني الثقة والمصداقية ويقرب الجمهور من اتخاذ خطوة.",
      challenges: "خبرة قوية من غير هيكل محتوى واضح ومستمر.",
      relevant: "تحديد المكانة واستراتيجية المحتوى وإدارة الحساب.",
      improve: "الوضوح والثقة ومسار أقوى من الخبرة إلى اتخاذ خطوة.",
    },
    {
      title: "الأنشطة المحلية",
      copy: "لو نشاطك بيعتمد على العملاء القريبين منك، ببني اتجاه محتوى يساعد الناس تعرف البراند، تتفاعل معاه وتفهم القيمة اللي بيقدمها.",
      challenges: "وعي محلي محدود وسبب غير واضح لاختيار البراند.",
      relevant: "استراتيجية المحتوى والإدارة والإعلانات المدفوعة.",
      improve: "الاكتشاف المحلي وفهم البراند والتفاعل الهادف.",
    },
  ],
} as const;

export const caseStudies = [
  { slug: "abq-al-hayat", name: { en: "ABQ AL HAYAT", ar: "عبق الحياة" }, title: { en: "ABQ AL HAYAT: Building a Content-Led Growth System", ar: "عبق الحياة: بناء منظومة نمو يقودها المحتوى" }, category: { en: "B2B content-led growth", ar: "نمو B2B يقوده المحتوى" }, coverImage: "https://i.ibb.co/h1rDjJ2m/Untitled-1-01.webp", summary: { en: "A case study showing how I connected content strategy, audience insights, paid media, sales feedback, and long-term digital assets to create measurable growth.", ar: "دراسة حالة توضح إزاي بنيت منظومة تربط استراتيجية المحتوى، فهم الجمهور، الإعلانات، بيانات المبيعات والأصول الرقمية لتحقيق نمو قابل للقياس." }, cta: { en: "View Case Study", ar: "استعرض دراسة الحالة" }, serviceTags: ["B2B Marketing", "Content Strategy", "Paid Media"], featured: true, published: true },
  { slug: "kham-al-jamal", name: { en: "Kham Al Jamal", ar: "خام الجمال" }, category: { en: "Brand content", ar: "محتوى البراند" }, coverImage: "https://i.ibb.co/gZtm5pNV/Untitled-1-02.webp", logo: null, summary: null, challenge: null, strategy: null, execution: null, results: null, gallery: [], videos: [], testimonial: null, serviceTags: ["Content", "Management"], featured: false, published: false },
  { slug: "lina", name: { en: "Lina", ar: "لينا" }, title: { en: "Lina: Building a Saudi Fashion Brand Through Storytelling", ar: "لينا: بناء براند أزياء سعودي من خلال القصة" }, category: { en: "Saudi fashion & e-commerce", ar: "أزياء سعودية ومتجر إلكتروني" }, coverImage: "https://i.ibb.co/hFq0ZY8w/Untitled-1-03.webp", summary: { en: "A culturally rooted brand system connecting persona design, audience psychology, AI content, storytelling, and e-commerce optimization.", ar: "منظومة براند محلية تربط بناء الشخصية، سيكولوجية الجمهور، محتوى الذكاء الاصطناعي، القصة وتطوير المتجر الإلكتروني." }, cta: { en: "View Case Study", ar: "استعرض دراسة الحالة" }, serviceTags: ["Brand Strategy", "Content", "AI Production", "SEO"], featured: false, published: true },
] as const;

export const abqCaseStudy = {
  website: "https://abqalhayat.com/",
  coverImage: "https://i.ibb.co/h1rDjJ2m/Untitled-1-01.webp",
  tags: ["B2B Marketing", "Content Strategy", "Social Media Management", "Paid Media", "Sales Alignment", "SEO", "Multilingual Markets"],
  media: [
    { youtubeId: "dXSrWXwzc3M", title: { en: "Why excellent projects may not reach the position they deserve", ar: "ليه مشاريع ممتازة ممكن ما توصلش للمكانة اللي تستحقها" } },
    { youtubeId: "4Dh3DvfOGNU", title: { en: "What investors should consider before starting a company in Saudi Arabia", ar: "إيه اللي لازم المستثمر يفكر فيه قبل تأسيس شركة في السعودية" } },
  ],
  en: {
    breadcrumb: "Case Studies",
    badge: "Featured Case Study",
    title: "ABQ AL HAYAT: Building a Content-Led Growth System",
    subtitle: "How I built an integrated system connecting content, audience psychology, sales insights, and paid media to turn marketing activity into a more sustainable growth engine.",
    imageAlt: "ABQ AL HAYAT company formation and investment services case study",
    overviewTitle: "Project Overview",
    overview: "ABQ AL HAYAT operates in company formation and investment services in Saudi Arabia. The challenge went beyond improving the appearance of the content; the project required a system that connected marketing with sales, addressed distinct audience segments, and produced consistent content whose impact could be measured and improved.",
    challengeTitle: "The Central Challenge",
    challenge: "Marketing activity, content production, sales feedback, and audience segments were operating without one connected system. My role was to create that connection, improve decision quality, and build a repeatable foundation for growth.",
    workstreamsTitle: "Five Connected Workstreams",
    challengeLabel: "Challenge",
    strategyLabel: "My Strategy",
    workstreams: [
      { title: "From Fragmented Content to a Structured Production System", challenge: "The content was unstructured, visual assets were fragmented, publishing was inconsistent, and the brand lacked a clear B2B tone of voice.", strategy: "I built an integrated content pipeline covering talent direction, organized asset delivery through Google Drive, scriptwriting, and clear guidance for the filming and editing teams. I also developed a more professional and consistent brand tone of voice." },
      { title: "Turning Client Stories into Credibility Assets", challenge: "Existing client success stories were underused, with no structured visual documentation or clear integration into the website and search strategy.", strategy: "I systemized testimonial video production from hook development and filming to delivery, publishing, and repurposing. I also improved the website content for search visibility and embedded client stories as proof that supports trust and conversion." },
      { title: "Rebuilding the Offer for the Urdu Market", challenge: "Urdu-segment contracts remained limited despite having a dedicated sales team because the offer and content did not align with the audience’s purchasing power and decision drivers.", strategy: "I studied the audience’s motivations, introduced a pricing structure suited to the segment, and rebuilt the messaging around speed, quality, and assurance. I also adopted a lighter, culturally relevant content style using trends and humor." },
      { title: "Increasing Publishing Consistency and Reducing Decision Friction", challenge: "Publishing was limited to one or two posts per week at best, while prospective clients went through a long decision cycle before signing.", strategy: "I introduced a diverse daily publishing schedule covering educational content, interactive formats, testimonials, and trends. I also repositioned the initial meeting as a free consultation, available online or at the office, so prospects could ask questions and review supporting documents before making a decision." },
      { title: "Connecting Marketing with Sales Insights", challenge: "The absence of regular communication between marketing and sales made it difficult to track lead quality and understand why campaigns succeeded or underperformed.", strategy: "I established a weekly meeting between Sales, Content, and the Media Buyer to review call feedback, comment patterns, and lead quality. I used those insights to continuously improve messaging, targeting, and content." },
    ],
    impactTitle: "Business Impact",
    impactIntro: "Approved results from the project period, presented without attributing every business outcome to marketing alone.",
    results: [
      { metric: "3.3×", label: "Monthly contracts", copy: "Monthly contracts increased from 18 in December 2025 to 60 in July 2026, representing 3.3× the original volume or an increase of approximately 233%." },
      { metric: "SAR 5", label: "Average cost per lead", copy: "Average cost per lead decreased from SAR 14–17 to SAR 5, while the Sports Register campaign achieved the best recorded CPL at SAR 1.99." },
      { metric: "4–5×", label: "Urdu-segment growth", copy: "Urdu-segment contracts grew from approximately 3 to 12–15 per month, representing 4–5× growth." },
      { metric: "Jeddah", label: "Geographic expansion", copy: "Sales feedback helped identify new geographic growth opportunities and informed the opening of the Jeddah branch in June." },
    ],
    channelsTitle: "Digital Channel Growth",
    channels: [
      { metric: "1,000%+", title: "YouTube views", copy: "YouTube views grew by more than 1,000% through a more structured video-content approach and optimized titles." },
      { metric: "35 → 1,300+", title: "Organic TikTok growth", copy: "TikTok grew organically from 35 to more than 1,300 followers and began generating inbound leads without TikTok ad spend." },
      { metric: "500%+", title: "Reach and engagement", copy: "Overall reach and engagement grew by more than 500% across the managed social media channels." },
    ],
    assetsTitle: "Long-Term Value Beyond Individual Campaigns",
    assets: [
      { title: "Repeatable Content System", copy: "I built a clear workflow for content production, asset organization, and consistent publishing." },
      { title: "Long-Term Digital Assets", copy: "I developed website content, a video library, and organic channels that could continue creating value beyond individual campaigns." },
      { title: "Marketing and Sales Feedback Loop", copy: "I created a consistent process for turning real market feedback into improvements in content and targeting." },
    ],
    takeawayTitle: "Strategic Takeaway",
    takeaway: "Sustainable B2B growth does not come from isolated campaigns. It comes from connecting content strategy, sales insights, and audience psychology. By building an integrated system and tailoring the offer to each segment, I helped turn content into part of a long-term growth engine rather than a series of disconnected posts.",
    mediaTitle: "Selected Video Content",
    mediaIntro: "A sample of the short-form video content produced for ABQ AL HAYAT. Play each video directly from the case study.",
    visit: "Visit ABQ AL HAYAT Website",
    visitLabel: "Visit ABQ AL HAYAT website - opens in a new tab",
    consultationTitle: "Need a content system connected to business growth?",
    consultationCopy: "Tell me about your business and current challenge, and I’ll help you identify the most useful starting point.",
  },
  ar: {
    breadcrumb: "دراسات الحالة",
    badge: "دراسة حالة رئيسية",
    title: "عبق الحياة: بناء منظومة نمو يقودها المحتوى",
    subtitle: "كيف بنيت منظومة متكاملة تربط المحتوى، سيكولوجية الجمهور، بيانات المبيعات والإعلانات لتحويل النشاط التسويقي إلى أداة نمو أكثر استدامة.",
    imageAlt: "دراسة حالة عبق الحياة لخدمات تأسيس الشركات والاستثمار",
    overviewTitle: "نظرة عامة على المشروع",
    overview: "عبق الحياة شركة تعمل في مجال تأسيس الشركات والاستثمار داخل المملكة العربية السعودية. كان التحدي أكبر من مجرد تحسين شكل المحتوى؛ المطلوب كان بناء منظومة تربط التسويق بالمبيعات، وتخاطب شرائح مختلفة، وتنتج محتوى مستمرًا يمكن قياس أثره وتطويره.",
    challengeTitle: "التحدي الرئيسي",
    challenge: "كان نشاط التسويق وإنتاج المحتوى وملاحظات المبيعات وشرائح الجمهور شغالين من غير منظومة واحدة تربطهم. دوري كان إني أبني الرابط ده، وأحسّن جودة القرارات، وأؤسس قاعدة قابلة للتكرار تدعم النمو.",
    workstreamsTitle: "خمس مسارات عمل مترابطة",
    challengeLabel: "التحدي",
    strategyLabel: "استراتيجيتي",
    workstreams: [
      { title: "من محتوى متفرق إلى منظومة إنتاج واضحة", challenge: "كان المحتوى غير منظم، والأصول المرئية متفرقة، ومعدل النشر غير ثابت، مع غياب نبرة صوت واضحة تناسب طبيعة جمهور الـB2B.", strategy: "بنيت منظومة محتوى متكاملة، بداية من اختيار وتوجيه المواهب، وتنظيم تسليم الأصول عبر Google Drive، وصولًا لكتابة السكريبتات وتوجيه فرق التصوير والمونتاج. كما طورت نبرة صوت أكثر احترافية وثباتًا للبراند." },
      { title: "تحويل قصص العملاء إلى دليل يبني الثقة", challenge: "كانت قصص نجاح العملاء السابقين غير مستغلة، مع غياب التوثيق المرئي المنظم وضعف الاستفادة منها في الموقع ومحركات البحث.", strategy: "نظمت عملية إنتاج فيديوهات تجارب العملاء بداية من صياغة الـHook، مرورًا بالتصوير والتسليم، وحتى النشر وإعادة الاستخدام. كما طورت محتوى الموقع ليكون أوضح لمحركات البحث، مع دمج قصص العملاء كدليل يدعم الثقة والتحويل." },
      { title: "إعادة بناء العرض والمحتوى لشريحة الأوردو", challenge: "كانت تعاقدات شريحة الأوردو محدودة جدًا رغم وجود فريق مبيعات مخصص، بسبب عدم توافق العرض والمحتوى مع القدرة الشرائية وسيكولوجية الجمهور.", strategy: "درست دوافع الجمهور الأوردو وطورت قائمة أسعار تناسب الشريحة، مع إعادة بناء الرسائل حول السرعة والجودة والضمان. كما استخدمت محتوى أخف وأقرب للثقافة المستهدفة من خلال الـTrends والـHumor." },
      { title: "زيادة انتظام المحتوى وتقليل التردد قبل التعاقد", challenge: "كان النشر يتم مرة أو مرتين أسبوعيًا في أفضل الحالات، مع دورة قرار طويلة قبل وصول العميل إلى خطوة التعاقد.", strategy: "رفعت معدل النشر إلى جدول يومي متنوع يشمل المحتوى التعليمي، التفاعلي، تجارب العملاء والـTrends. كما حولت الاجتماع الأول إلى استشارة مجانية أونلاين أو داخل مقر الشركة، علشان يقدر العميل يسأل ويطّلع على المستندات قبل اتخاذ القرار." },
      { title: "ربط التسويق ببيانات المبيعات", challenge: "غياب التواصل المنتظم بين التسويق والمبيعات صعّب تتبع جودة العملاء المحتملين ومعرفة أسباب نجاح أو ضعف الحملات.", strategy: "أسست اجتماعًا أسبوعيًا يجمع المبيعات وصناع المحتوى والميديا باير لمراجعة ملاحظات المكالمات، أنماط التعليقات وجودة العملاء المحتملين. استخدمت البيانات دي في تحسين الرسائل والاستهداف والمحتوى باستمرار." },
    ],
    impactTitle: "أثر المشروع على البيزنس",
    impactIntro: "النتائج المعتمدة خلال فترة المشروع، مع تجنب نسب كل نتيجة في البيزنس إلى التسويق وحده.",
    results: [
      { metric: "3.3×", label: "التعاقدات الشهرية", copy: "نمت التعاقدات الشهرية من 18 عقدًا في ديسمبر 2025 إلى 60 عقدًا في يوليو 2026، بما يعادل 3.3 أضعاف أو زيادة تقارب 233%." },
      { metric: "5 ريالات", label: "متوسط تكلفة العميل المحتمل", copy: "انخفض متوسط تكلفة العميل المحتمل من 14–17 ريالًا إلى 5 ريالات، بينما حققت حملة السجل الرياضي أفضل تكلفة مسجلة بلغت 1.99 ريال للعميل المحتمل." },
      { metric: "4–5×", label: "نمو شريحة الأوردو", copy: "نمت تعاقدات شريحة الأوردو من نحو 3 تعاقدات إلى 12–15 تعاقدًا شهريًا، بما يعادل نموًا يتراوح بين 4 و5 أضعاف." },
      { metric: "جدة", label: "التوسع الجغرافي", copy: "ساهمت ملاحظات فريق المبيعات في تحديد فرص نمو جغرافية جديدة ودعمت قرار افتتاح فرع جدة في يونيو." },
    ],
    channelsTitle: "نمو القنوات الرقمية",
    channels: [
      { metric: "+1000%", title: "مشاهدات YouTube", copy: "نمت مشاهدات YouTube بأكثر من 1000% من خلال تنظيم المحتوى المرئي وتحسين صياغة العناوين." },
      { metric: "+1,300 ← 35", title: "نمو TikTok العضوي", copy: "نمت قناة TikTok من 35 إلى أكثر من 1,300 متابع بشكل عضوي، وبدأت في جذب عملاء محتملين بدون إنفاق إعلاني على TikTok." },
      { metric: "+500%", title: "الوصول والتفاعل", copy: "نمت معدلات الوصول والتفاعل إجمالًا بأكثر من 500% عبر قنوات السوشيال ميديا التي أدرتها." },
    ],
    assetsTitle: "أثر مستمر يتجاوز مدة الحملة",
    assets: [
      { title: "منظومة محتوى قابلة للتكرار", copy: "بنيت Workflow واضحًا لإنتاج المحتوى وتنظيم الأصول المرئية واستمرار النشر." },
      { title: "أصول رقمية طويلة الأجل", copy: "طورت محتوى للموقع، ومكتبة فيديو، وقنوات عضوية يمكن البناء عليها بدل الاعتماد على حملات مؤقتة فقط." },
      { title: "حلقة مستمرة بين التسويق والمبيعات", copy: "أنشأت طريقة منتظمة لتحويل ملاحظات السوق إلى تحسينات في المحتوى والاستهداف." },
    ],
    takeawayTitle: "الخلاصة الاستراتيجية",
    takeaway: "النمو الحقيقي في الـB2B مش نتيجة حملة منفصلة. بيبدأ من الربط بين استراتيجية المحتوى، بيانات المبيعات وسيكولوجية الجمهور. لما بنيت المنظومة بشكل متكامل وطورت العرض لكل شريحة، المحتوى بقى جزءًا من محرك نمو مستدام بدل ما يفضل مجرد منشورات.",
    mediaTitle: "نماذج من محتوى الفيديو",
    mediaIntro: "نماذج من محتوى الفيديو القصير الذي تم إنتاجه لعبق الحياة. تقدر تشغّل كل فيديو مباشرة من دراسة الحالة.",
    visit: "زيارة موقع عبق الحياة",
    visitLabel: "زيارة موقع عبق الحياة - يفتح في نافذة جديدة",
    consultationTitle: "محتاج منظومة محتوى مرتبطة بنمو البيزنس؟",
    consultationCopy: "احكيلي عن البيزنس والتحدي الحالي، وأنا أساعدك تحدد أنسب نقطة بداية.",
  },
} as const;

export const linaCaseStudy = {
  website: "https://linnaaa.com/",
  coverImage: "https://i.ibb.co/hFq0ZY8w/Untitled-1-03.webp",
  gallery: [
    { src: "/case-studies/lina/lina-persona.jpeg", alt: { en: "Lina visual persona in a butterfly-inspired creative studio", ar: "شخصية لينا البصرية داخل استوديو مستوحى من الفراشات" } },
    { src: "/case-studies/lina/lina-storyboard.jpeg", alt: { en: "Lina brand persona storytelling storyboard", ar: "لوحة سرد بصري لشخصية لينا وقصة البراند" } },
    { src: "/case-studies/lina/lina-collection.jpeg", alt: { en: "Lina abaya collection and brand storytelling visuals", ar: "مجموعة عبايات لينا ومشاهد القصة البصرية للبراند" } },
  ],
  videos: [
    { src: "/case-studies/lina/lina-video-1.mp4", title: { en: "Lina AI brand video 1", ar: "فيديو براند لينا بالذكاء الاصطناعي 1" } },
    { src: "/case-studies/lina/lina-video-2.mp4", title: { en: "Lina AI brand video 2", ar: "فيديو براند لينا بالذكاء الاصطناعي 2" } },
    { src: "/case-studies/lina/lina-video-3.mp4", title: { en: "Lina AI brand video 3", ar: "فيديو براند لينا بالذكاء الاصطناعي 3" } },
  ],
  tags: ["Brand Strategy", "Saudi Fashion", "AI Content", "Storytelling", "E-commerce", "SEO"],
  en: {
    breadcrumb: "Case Studies",
    badge: "Brand Building Case Study",
    title: "Lina: Building a Saudi Fashion Brand Through Storytelling",
    subtitle: "How I shaped an authentic Saudi brand persona, translated audience psychology into a distinctive offer, and connected AI-powered storytelling with an optimized e-commerce experience.",
    imageAlt: "Lina Saudi fashion brand persona painting a butterfly",
    overviewTitle: "Project Overview",
    overview: "Lina is a Saudi fashion and abaya brand shaped around a culturally rooted character rather than a generic commercial identity. I developed the brand story, persona, content direction, competitive benefits, and digital shopping experience as one connected system.",
    challengeTitle: "The Brand Opportunity",
    challenge: "The opportunity was to turn a business investment into a brand people could recognize, feel connected to, and choose for reasons beyond the product alone.",
    pillarsTitle: "Four Connected Brand-Building Pillars",
    pillars: [
      { title: "Brand Story & Identity", points: ["I conceptualized and brought Lina to life as an authentic Saudi persona inspired by Al Baha’s natural beauty, drawing, and butterflies.", "Her story informed the visual identity, logo, and brand narrative, connecting Saudi craftsmanship, women’s empowerment, and local pride."] },
      { title: "Audience Psychology & Competitive Edge", points: ["I aligned the positioning and offers with Saudi consumer behavior and the desire to support local heritage and businesses.", "The offer introduced made-to-order production, custom sizing, free post-delivery alterations, and complimentary shipping to create a meaningful competitive advantage."] },
      { title: "AI Integration & Content Production", points: ["I generated a consistent AI-powered visual persona for Lina that embodied the brand’s spirit and values.", "I used AI production tools to create dynamic promotional videos and content that brought the character and brand story to life."] },
      { title: "Storytelling & E-Commerce Optimization", points: ["I wrote stories around Lina’s persona, including how she sketched the logo, and created behind-the-scenes packaging and order-fulfillment content.", "I optimized store content, product copy, visual hierarchy, navigation, and SEO, helping Lina reach the first page of Google search results."] },
    ],
    benefitsTitle: "A Distinctive Customer Promise",
    benefits: ["Made to order", "Custom sizing", "Free post-delivery alterations", "Complimentary shipping"],
    seoEyebrow: "Search & Shopping Experience",
    seoTitle: "From brand discovery to a stronger buying journey",
    seoCopy: "The brand story continued inside the online store through clearer product copy, stronger visual organization, easier navigation, and search-focused content designed to improve discoverability and support conversion.",
    galleryTitle: "The Visual World of Lina",
    galleryIntro: "A visual system built around art, butterflies, warmth, and a distinctly Saudi character.",
    videosTitle: "AI-Powered Brand Content",
    videosIntro: "Selected promotional videos created to give Lina movement, personality, and a consistent presence across digital channels.",
    takeawayTitle: "Strategic Takeaway",
    takeaway: "Lina shows how a strong character can become the connective tissue between identity, content, customer experience, and commercial differentiation. The result is not only a visual brand, but a story the audience can enter and remember.",
    visit: "Visit Lina Store",
    visitLabel: "Visit Lina online store - opens in a new tab",
    consultationTitle: "Need a brand story people can recognize and remember?",
    consultationCopy: "Tell me about your business, audience, and offer, and I’ll help you identify the strongest starting point.",
  },
  ar: {
    breadcrumb: "دراسات الحالة",
    badge: "دراسة حالة لبناء براند",
    title: "لينا: بناء براند أزياء سعودي من خلال القصة",
    subtitle: "كيف بنيت شخصية سعودية أصيلة، وحولت سيكولوجية الجمهور إلى عرض تنافسي واضح، وربطت المحتوى القصصي بالذكاء الاصطناعي وتجربة متجر إلكتروني أفضل.",
    imageAlt: "لوجو لينا لبراند الأزياء السعودي",
    overviewTitle: "نظرة عامة على المشروع",
    overview: "لينا براند سعودي للأزياء والعبايات تم بناؤه حول شخصية محلية لها قصة، وليس مجرد هوية تجارية عامة. طورت قصة البراند، الشخصية، اتجاه المحتوى، المزايا التنافسية وتجربة التسوق الرقمية كمنظومة واحدة مترابطة.",
    challengeTitle: "فرصة بناء البراند",
    challenge: "الفرصة كانت تحويل استثمار تجاري إلى براند يقدر الجمهور يتعرف عليه، يرتبط به عاطفيًا، ويختاره لأسباب تتجاوز المنتج وحده.",
    pillarsTitle: "أربعة محاور مترابطة لبناء البراند",
    pillars: [
      { title: "قصة وهوية العلامة التجارية", points: ["ابتكرت شخصية لينا كشخصية سعودية أصيلة مستوحاة من جمال طبيعة الباحة وشغفها بالرسم والفراشات.", "انعكست القصة على الهوية البصرية والشعار وسرد البراند، وربطت الحرفية السعودية بتمكين المصممات والفخر المحلي."] },
      { title: "سيكولوجية الجمهور والميزة التنافسية", points: ["ربطت تموضع البراند وعروضه بالسلوك الاستهلاكي السعودي وتقدير الجمهور للمنتجات المحلية والتراث الوطني.", "شمل العرض التفصيل عند الطلب، تخصيص المقاسات، تعديلات مجانية بعد الاستلام، وشحنًا مجانيًا لبناء ميزة تنافسية واضحة." ] },
      { title: "الذكاء الاصطناعي وإنتاج المحتوى", points: ["صممت شخصية بصرية ثابتة للينا باستخدام أدوات الذكاء الاصطناعي لتعكس روح البراند وقيمه.", "وظفت تقنيات الذكاء الاصطناعي لإنتاج فيديوهات ترويجية ومحتوى ديناميكي يمنح الشخصية والقصة حضورًا حيًا." ] },
      { title: "المحتوى القصصي وتطوير المتجر", points: ["كتبت محتوى قصصيًا حول شخصية لينا، مثل قصة رسم الشعار، وقدمت كواليس تجهيز وتغليف الطلبات لإشراك الجمهور في رحلة البيع.", "حسنت محتوى المتجر ووصف المنتجات والتنظيم البصري والتنقل وSEO، وساعد ذلك لينا على الظهور في الصفحة الأولى من نتائج بحث Google." ] },
    ],
    benefitsTitle: "وعد واضح ومميز للعميل",
    benefits: ["تفصيل عند الطلب", "تخصيص المقاسات", "تعديلات مجانية بعد الاستلام", "شحن مجاني"],
    seoEyebrow: "البحث وتجربة التسوق",
    seoTitle: "من اكتشاف البراند إلى رحلة شراء أقوى",
    seoCopy: "استمرت قصة البراند داخل المتجر من خلال وصف منتجات أوضح، وتنظيم بصري أقوى، وتنقل أسهل، ومحتوى مهيأ لمحركات البحث لتحسين الظهور ودعم التحويل.",
    galleryTitle: "العالم البصري للينا",
    galleryIntro: "منظومة بصرية تجمع الفن والفراشات والدفء وشخصية سعودية واضحة.",
    videosTitle: "محتوى البراند بالذكاء الاصطناعي",
    videosIntro: "نماذج من الفيديوهات الترويجية التي منحت لينا حركة وشخصية وحضورًا متسقًا عبر القنوات الرقمية.",
    takeawayTitle: "الخلاصة الاستراتيجية",
    takeaway: "توضح لينا إزاي يمكن لشخصية قوية أن تربط الهوية والمحتوى وتجربة العميل والتميّز التجاري. النتيجة ليست مجرد براند بصري، بل قصة يقدر الجمهور يدخل عالمها ويتذكرها.",
    visit: "زيارة متجر لينا",
    visitLabel: "زيارة متجر لينا الإلكتروني - يفتح في نافذة جديدة",
    consultationTitle: "محتاج قصة براند يقدر جمهورك يتعرف عليها ويفتكرها؟",
    consultationCopy: "احكيلي عن البيزنس والجمهور والعرض، وأنا أساعدك تحدد أقوى نقطة بداية.",
  },
} as const;

export const auditAreas = [
  { id: "profile", en: "Profile clarity", ar: "وضوح الملف التعريفي" },
  { id: "audience", en: "Audience and positioning", ar: "الجمهور وتحديد المكانة" },
  { id: "direction", en: "Content direction", ar: "اتجاه المحتوى" },
  { id: "consistency", en: "Content consistency", ar: "استمرارية المحتوى" },
  { id: "creative", en: "Creative quality", ar: "جودة المحتوى الإبداعي" },
  { id: "engagement", en: "Engagement patterns", ar: "أنماط التفاعل" },
  { id: "performance", en: "Performance indicators", ar: "مؤشرات الأداء" },
  { id: "journey", en: "Customer journey", ar: "رحلة العميل" },
  { id: "conversion", en: "Conversion opportunities", ar: "فرص التحويل" },
  { id: "priorities", en: "Improvement priorities", ar: "أولويات التحسين" },
] as const;

export const processSteps = {
  en: [["Understand", "I clarify the business, audience, objectives, and current challenge."], ["Strategize", "I define the direction, priorities, channels, and role of content."], ["Create", "I turn the strategy into purposeful content and practical execution."], ["Measure", "I review the indicators connected to the agreed business objective."], ["Optimize", "I use what I learn to refine the next decisions and actions."]],
  ar: [["أفهم", "بوضح طبيعة البيزنس والجمهور والأهداف والتحدي الحالي."], ["أخطط", "بحدد الاتجاه والأولويات والقنوات ودور المحتوى."], ["أنفذ", "بحوّل الاستراتيجية إلى محتوى هادف وتنفيذ عملي."], ["أقيس", "براجع المؤشرات المرتبطة بهدف البيزنس المتفق عليه."], ["أطوّر", "بستخدم اللي اتعلمته علشان أطوّر القرارات والخطوات الجاية."]],
} as const;

const faqItems = {
  en: [
    ["Do you work with every type of business?", "I first review the business, audience, and challenge to confirm whether the collaboration is a suitable fit."],
    ["Does the service include content creation?", "Content requirements depend on the selected service and scope. I clarify what is included during the consultation."],
    ["Do you manage paid advertising?", "Yes, paid media management is available when the business has a clear objective, offer, and suitable starting point."],
    ["Can I start with one service?", "Yes. I can begin with the most relevant priority and define any additional needs later."],
    ["Is there a monthly contract?", "The working format depends on the service and scope. I discuss the suitable arrangement with you before starting."],
    ["How do you measure social media success?", "I agree on indicators with you that connect to the business objective instead of relying only on visible platform metrics."],
    ["I am not sure which service I need. Where should I start?", "Start with a consultation or account audit so I can understand the current situation and define the priority."],
  ],
  ar: [
    ["هل بتشتغلي مع كل أنواع البيزنس؟", "براجع طبيعة البيزنس والجمهور والتحدي الأول علشان أتأكد إن التعاون مناسب."],
    ["هل الخدمة تشمل صناعة المحتوى؟", "احتياجات المحتوى بتختلف حسب الخدمة ونطاق العمل، وبوضح بالتحديد إيه المشمول خلال الاستشارة."],
    ["هل بتقدمي إدارة للإعلانات المدفوعة؟", "نعم، إدارة الإعلانات متاحة لما يكون للبيزنس هدف وعرض ونقطة بداية واضحة."],
    ["هل أقدر أبدأ بخدمة واحدة؟", "نعم، أقدر أبدأ معاك بالأولوية الأكثر صلة وأحدد أي احتياجات إضافية بعد كده."],
    ["هل فيه تعاقد شهري؟", "شكل العمل بيتحدد حسب الخدمة ونطاقها، وبناقش معاك الترتيب المناسب قبل البداية."],
    ["إزاي بتقيسي نجاح السوشيال ميديا؟", "بتفق معاك على مؤشرات مرتبطة بهدف البيزنس بدل الاعتماد على الأرقام الظاهرة على المنصة فقط."],
    ["مش عارف الخدمة المناسبة، أبدأ منين؟", "ابدأ باستشارة أو تحليل للحساب علشان أفهم الوضع الحالي وأحدد الأولوية."],
  ],
} as const;

export const copy = {
  en: {
    languageLabel: "العربية",
    menu: "Menu",
    book: "Book a Consultation",
    common: { eyebrow: "Habiba Dapour", learn: "Learn more", caseSoon: "Case study details coming soon", featured: "Featured Case Study", processTitle: "Understand. Strategize. Create. Measure. Optimize.", processIntro: "My work does not begin with a posting calendar. I start by understanding the business, then build, execute, measure, and improve.", whatsappMessage: "Hi Habiba, I would like to book a social media consultation." },
    footer: { heading: "Ready for a clearer social media direction?", copy: "Tell me about your business, challenge, and priorities.", contact: "Contact", location: "Marsa Matrouh, Egypt · Available worldwide", explore: "Explore" },
    home: {
      eyebrow: "Strategic social media for growing businesses",
      title: "I help turn social media into a real channel for business growth.",
      intro: "I’m a Senior Social Media Specialist & Growth Strategist. My role goes beyond managing accounts; I build strategy and content systems that help businesses unlock new growth opportunities and turn social media into a channel with measurable business impact.",
      work: "Explore My Work",
      imageAlt: "Habiba Dapour, Senior Social Media Specialist and Growth Strategist",
      problemTitle: "Your social media is active—but is it actually helping the business?",
      problems: ["You publish consistently but generate few leads.", "You have followers but limited business impact.", "Your content lacks a clear strategy.", "Your ads bring traffic without enough conversions.", "You are managing everything yourself instead of focusing on the business."],
      problemClose: "If any of these challenges sound familiar, I can identify what is holding the account back and define a clearer way forward.",
      aboutTitle: "Strategy before posting. Business impact before vanity metrics.",
      aboutCopy: "I start by understanding the business, audience, and objectives before deciding what to publish. I connect strategy, content, management, and performance analysis so social media becomes a meaningful part of business growth.",
      aboutCta: "Learn More About My Approach",
      servicesTitle: "Services Built Around Business Needs",
      helpTitle: "Who I Help",
      casesTitle: "Selected Case Studies",
      casesIntro: "Explore the thinking and work behind each project, from understanding the challenge and building the strategy to execution and improvement.",
      casesCta: "Explore All Case Studies",
      pathwaysTitle: "Find the right place to start",
      pathways: [["About", "See the principles and process behind my work.", "/about"], ["Services", "Explore management, strategy, audits, and paid media.", "/services"], ["Who I Help", "Find the approach that matches your business challenge.", "/who-we-help"], ["Case Studies", "Explore selected projects and my way of thinking.", "/case-studies"], ["Social Media Audit", "Identify weaknesses, opportunities, and improvement priorities.", "/social-media-audit"], ["Book a Consultation", "Tell me about the business and define the next step.", "/contact"]],
      finalTitle: "Not sure whether your account needs management, a strategy, or an audit?",
      finalCopy: "Start with a consultation so I can understand the challenge and identify the right next step.",
    },
    services: { eyebrow: "Services", title: "I do not deliver isolated posts. I build a system around your business goals.", intro: "Every service starts with the current business situation and connects strategy, execution, and measurement to a clear objective.", labels: ["The customer problem", "Best suited for", "What it covers", "Intended business outcome"], decisionTitle: "Not sure which service to start with?", decisionCopy: "I can begin with an account audit or a consultation to understand the current situation and define the priorities." },
    help: { eyebrow: "Who I Help", title: "Different Businesses. Different Challenges. The Right Approach.", intro: "The right social media system depends on how the business grows, sells, and builds trust.", labels: ["Common challenges", "Relevant services", "What collaboration can improve"] },
    cases: { eyebrow: "My Work", title: "Case Studies", intro: "I do not present isolated designs or posts. Each completed project shows the challenge, strategic thinking, execution, and the content system developed around it." },
    about: { eyebrow: "About", title: "A Growth Partner, Not Just Account Management.", body: "I’m a Senior Social Media Specialist & Growth Strategist. My role goes beyond managing accounts; I build strategy and content systems that help businesses unlock new growth opportunities and turn social media into a channel with measurable business impact.", imageAlt: "Habiba Dapour", valuesTitle: "The principles behind my work", values: [["Strategy First", "Every step begins with understanding the business goals—not choosing the appearance of a post."], ["Creativity with Purpose", "I develop ideas suited to the brand and audience while serving a clear purpose."], ["Data & Transparency", "I review performance openly and make decisions using actual data."], ["Partnership & Progress", "I approach every project as an ongoing partnership focused on learning, improvement, and growth."]] },
    faq: { title: "Frequently Asked Questions", items: faqItems.en },
    contact: { eyebrow: "Contact", title: "Tell Me About Your Business.", intro: "Share a few details about your business and current challenge. I’ll review them to identify the most suitable starting point before getting in touch.", labels: ["Name", "Business name", "Email", "Phone number", "Country", "Business type", "Instagram or website URL", "Main current challenge", "Service of interest", "Monthly marketing budget", "Preferred contact method", "Additional details"], challenges: ["Content strategy", "Account management", "Paid advertising", "Performance and conversions", "Generating leads", "Not sure yet"], serviceOptions: ["Social Media Management", "Content Strategy", "Social Media Audit", "Paid Media Management", "Consultation", "Not sure yet"], methods: ["WhatsApp", "Email", "Phone call"], select: "Select an option", submit: "Book a Consultation", success: "I’ve received your details. I’ll review the challenge and contact you to define the right next step.", successNote: "Your prepared request has opened in WhatsApp. Send it to complete your request." },
    audit: { eyebrow: "Social Media Audit", title: "Not Sure What Is Holding Your Account Back?", intro: "Through a structured account audit, I review your current content and performance to identify weaknesses, opportunities, and the most important improvement actions.", areasTitle: "What I can review", formTitle: "Request your account audit", formIntro: "Tell me about the account and choose the areas you want me to review.", sections: ["About you and the business", "About the account", "Areas to review"], labels: ["Name", "Business name", "Email", "Phone number", "Country", "Primary platform", "Account URL", "Main business goal", "Main current challenge", "Additional context"], consent: "I confirm these details are accurate and agree to be contacted about this request.", platforms: ["Instagram", "Facebook", "TikTok", "LinkedIn", "Multiple platforms"], help: "Choose all relevant areas.", submit: "Request an Account Audit", success: "I’ve received your audit details. I’ll review the account context and contact you about the next appropriate step.", actions: ["Send by email", "Print request", "Edit details"] },
  },
  ar: {
    languageLabel: "English",
    menu: "القائمة",
    book: "احجز استشارتك",
    common: { eyebrow: "Habiba Dapour", learn: "اعرف أكتر", caseSoon: "تفاصيل دراسة الحالة قريبًا", featured: "دراسة حالة رئيسية", processTitle: "أفهم. أخطط. أنفذ. أقيس. أطوّر.", processIntro: "شغلي مش بيبدأ بجدول بوستات. ببدأ بفهم البيزنس، وبعدها ببني وأنفذ وأقيس وأطوّر.", whatsappMessage: "مرحبًا Habiba، أرغب في حجز استشارة للسوشيال ميديا." },
    footer: { heading: "جاهز لاتجاه أوضح على السوشيال ميديا؟", copy: "احكيلي عن البيزنس والتحدي والأولويات.", contact: "تواصل معايا", location: "مرسى مطروح، مصر · متاحة للعمل مع العملاء في أي مكان", explore: "استكشف" },
    home: {
      eyebrow: "سوشيال ميديا استراتيجية للبيزنس الطموح",
      title: "أساعدك على تطوير ظهورك على السوشيال ميديا.",
      intro: "أنا Senior Social Media Specialist & Growth Strategist. دوري مش مجرد إدارة الحسابات؛ بشتغل على بناء استراتيجية ومحتوى يساعد البيزنس يفتح فرص نمو جديدة ويحوّل السوشيال ميديا إلى قناة لها تأثير واضح على النتائج.",
      work: "شوف سابقة أعمالي",
      imageAlt: "Habiba Dapour، خبيرة سوشيال ميديا واستراتيجية نمو",
      problemTitle: "السوشيال ميديا عندك شغالة… بس هل بتخدم البيزنس؟",
      problems: ["بتنشر باستمرار لكن مفيش عملاء محتملين؟", "عندك متابعين لكن تأثيرهم على المبيعات ضعيف؟", "المحتوى عشوائي ومفيش استراتيجية واضحة؟", "الإعلانات بتجيب زيارات من غير تحويلات كفاية؟", "بتدير كل حاجة بنفسك ومش لاقي وقت للبيزنس؟"],
      problemClose: "لو واحدة من المشاكل دي بتحصل معاك، أقدر أحدد السبب وأبني معاك نقطة بداية أوضح.",
      aboutTitle: "استراتيجية قبل النشر، ونتائج قبل الأرقام الشكلية.",
      aboutCopy: "ببدأ بفهم البيزنس والجمهور والأهداف قبل ما أقرر هنشر إيه. بربط بين الاستراتيجية والمحتوى والإدارة وتحليل الأداء علشان السوشيال ميديا تكون جزءًا حقيقيًا من رحلة نمو البيزنس.",
      aboutCta: "اعرف أكتر عن طريقتي",
      servicesTitle: "خدمات تبدأ من احتياج البيزنس",
      helpTitle: "مين أقدر أساعد؟",
      casesTitle: "سابقة أعمالي",
      casesIntro: "هنا بعرض طريقة التفكير والعمل وراء كل مشروع، من فهم التحدي ووضع الاستراتيجية إلى التنفيذ والتطوير.",
      casesCta: "شوف كل المشاريع",
      pathwaysTitle: "اختار نقطة البداية المناسبة",
      pathways: [["عن Habiba Dapour", "اتعرف على المبادئ وطريقة العمل اللي بعتمد عليها.", "/about"], ["الخدمات", "استكشف الإدارة والاستراتيجية والتحليل والإعلانات المدفوعة.", "/services"], ["مين أقدر أساعد", "شوف النهج المناسب لنوع البيزنس والتحدي اللي بتواجهه.", "/who-we-help"], ["سابقة الأعمال", "استكشف مشروعات مختارة وطريقة تفكيري فيها.", "/case-studies"], ["تحليل السوشيال ميديا", "حدد نقاط الضعف والفرص وأولويات التحسين.", "/social-media-audit"], ["احجز استشارتك", "احكيلي تفاصيل البيزنس وحدد الخطوة الجاية.", "/contact"]],
      finalTitle: "مش عارف حسابك محتاج إدارة، استراتيجية ولا تحليل؟",
      finalCopy: "ابدأ باستشارة أفهم فيها التحدي وأحدد معاك أنسب خطوة للبيزنس.",
    },
    services: { eyebrow: "الخدمات", title: "مش بقدم بوستات منفصلة؛ ببني منظومة تخدم هدف البيزنس.", intro: "كل خدمة ببدأها من وضع البيزنس الحالي وبربط الاستراتيجية والتنفيذ والقياس بهدف واضح.", labels: ["مشكلة العميل", "مناسبة لمين", "الخدمة تشمل", "النتيجة المستهدفة للبيزنس"], decisionTitle: "مش متأكد تبدأ بأنهي خدمة؟", decisionCopy: "أقدر أبدأ معاك بتحليل للحساب أو استشارة أفهم من خلالها الوضع الحالي وأحدد الأولويات." },
    help: { eyebrow: "مين أقدر أساعد", title: "حلول مختلفة حسب نوع البيزنس والتحدي", intro: "نظام السوشيال ميديا المناسب بيتغير حسب طريقة نمو البيزنس وبيعه وبنائه للثقة.", labels: ["تحديات شائعة", "الخدمات المناسبة", "إيه اللي ممكن أطوره"] },
    cases: { eyebrow: "أعمالي", title: "سابقة الأعمال", intro: "مش بعرض تصاميم أو بوستات منفصلة وبس. كل مشروع مكتمل هنا بيعرض التحدي وطريقة التفكير والاستراتيجية والتنفيذ ومنظومة المحتوى اللي طورتها." },
    about: { eyebrow: "عن Habiba Dapour", title: "شريكة نمو، مش مجرد إدارة حسابات.", body: "أنا Senior Social Media Specialist & Growth Strategist. دوري مش مجرد إدارة الحسابات؛ بشتغل على بناء استراتيجية ومحتوى يساعد البيزنس يفتح فرص نمو جديدة ويحوّل السوشيال ميديا إلى قناة لها تأثير واضح على النتائج.", imageAlt: "Habiba Dapour", valuesTitle: "المبادئ اللي بتحرك شغلي", values: [["الاستراتيجية أولًا", "كل خطوة ببدأها من فهم أهداف البيزنس، مش من اختيار شكل البوست."], ["إبداع له هدف", "بطور أفكار تناسب طبيعة البراند والجمهور وتخدم رسالة واضحة."], ["البيانات والوضوح", "براجع الأداء بوضوح وباخد قراراتي بناءً على البيانات الفعلية."], ["الشراكة والتطوير", "بتعامل مع كل مشروع كشراكة مستمرة هدفها التعلم والتحسين والنمو."]] },
    faq: { title: "أسئلة شائعة", items: faqItems.ar },
    contact: { eyebrow: "تواصل معايا", title: "احكيلي أكتر عن البيزنس.", intro: "شاركني معلومات بسيطة عن مشروعك والتحدي الحالي، وأنا هراجعها علشان أحدد أنسب نقطة بداية قبل ما أتواصل معاك.", labels: ["الاسم", "اسم البيزنس", "البريد الإلكتروني", "رقم الهاتف", "الدولة", "نوع البيزنس", "رابط الحساب أو الموقع", "أكبر تحدٍ حالي", "الخدمة المطلوبة", "الميزانية التسويقية الشهرية", "وسيلة التواصل المفضلة", "تفاصيل إضافية"], challenges: ["استراتيجية المحتوى", "إدارة الحساب", "الإعلانات المدفوعة", "الأداء والتحويلات", "توليد عملاء محتملين", "مش متأكد لسه"], serviceOptions: ["إدارة حسابات السوشيال ميديا", "استراتيجية المحتوى", "تحليل السوشيال ميديا", "إدارة الإعلانات المدفوعة", "استشارة", "مش متأكد لسه"], methods: ["واتساب", "البريد الإلكتروني", "مكالمة هاتفية"], select: "اختر من القائمة", submit: "احجز استشارتك", success: "وصلتني بياناتك. هراجع التحدي وأتواصل معاك علشان نحدد الخطوة المناسبة.", successNote: "طلبك المجهز اتفتح في واتساب. أرسله علشان تكمل الطلب." },
    audit: { eyebrow: "تحليل السوشيال ميديا", title: "مش عارف إيه اللي موقف نمو حسابك؟", intro: "من خلال تحليل الحساب، براجع الوضع الحالي للمحتوى والأداء وبحدد أهم نقاط الضعف والفرص والخطوات المطلوبة للتحسين.", areasTitle: "إيه اللي ممكن أراجعه؟", formTitle: "اطلب تحليل حسابك", formIntro: "شاركني معلومات الحساب وحدد الجوانب اللي محتاجني أراجعها.", sections: ["عنك وعن البيزنس", "عن الحساب", "جوانب التحليل"], labels: ["الاسم", "اسم البيزنس", "البريد الإلكتروني", "رقم الهاتف", "الدولة", "المنصة الأساسية", "رابط الحساب", "هدف البيزنس الأساسي", "أكبر تحدٍ حالي", "تفاصيل إضافية"], consent: "أؤكد أن البيانات صحيحة وأوافق على التواصل معي بخصوص هذا الطلب.", platforms: ["إنستجرام", "فيسبوك", "تيك توك", "لينكدإن", "أكثر من منصة"], help: "اختر كل الجوانب المناسبة.", submit: "اطلب تحليل حسابك", success: "وصلتني بيانات التحليل. هراجع سياق الحساب وأتواصل معاك بخصوص الخطوة المناسبة.", actions: ["أرسل بالبريد", "اطبع الطلب", "عدل البيانات"] },
  },
} as const;
