export type Language = "en" | "ar";

export const profileImageUrl = "https://i.ibb.co/Z1vvQmQ0/2.webp";
export const whatsappUrl = "https://wa.me/201004658868";

export const navigation = {
  en: [
    ["Home", "/"],
    ["Services", "/services"],
    ["Who We Help", "/who-we-help"],
    ["Case Studies", "/case-studies"],
    ["About", "/about"],
    ["Contact", "/contact"],
  ],
  ar: [
    ["الرئيسية", "/"],
    ["الخدمات", "/services"],
    ["مين نقدر نساعد", "/who-we-help"],
    ["سابقة الأعمال", "/case-studies"],
    ["عن Habiba Dapour", "/about"],
    ["تواصل معنا", "/contact"],
  ],
} as const;

export const services = {
  en: [
    {
      id: "management",
      title: "Social Media Management",
      preview: "From planning and publishing to account monitoring and performance analysis, we manage your social media through a strategy connected to your business goals.",
      problem: "The account is active, but daily decisions are disconnected and difficult to sustain.",
      fit: "Businesses that need consistent ownership aligned with wider priorities.",
      covers: ["Planning and publishing", "Account monitoring", "Community direction", "Performance reviews"],
      outcome: "A clearer, more consistent management system connected to the business.",
      cta: "Discuss Account Management",
    },
    {
      id: "strategy",
      title: "Content Strategy",
      preview: "We turn your business goals and ideas into a clear content direction that defines the audience, messaging, content pillars, and the role of each piece in the customer journey.",
      problem: "Content feels random, repetitive, or disconnected from the audience and customer journey.",
      fit: "Brands with ideas and expertise that need a structured direction before producing more content.",
      covers: ["Audience and positioning", "Messaging", "Content pillars", "Customer-journey roles"],
      outcome: "A purposeful content direction that guides decisions and production.",
      cta: "Build Your Content Direction",
    },
    {
      id: "audit",
      title: "Social Media Audit",
      preview: "We review your accounts, content, and performance to identify weaknesses, opportunities, and the most important actions for improvement.",
      problem: "You can see activity and data, but the causes of weak performance are still unclear.",
      fit: "Businesses that need an informed starting point before changing strategy or management.",
      covers: ["Profile and positioning", "Content direction", "Performance indicators", "Improvement priorities"],
      outcome: "A clearer view of the current situation and the most relevant next actions.",
      cta: "Request an Account Audit",
    },
    {
      id: "paid-media",
      title: "Paid Media Management",
      preview: "We plan and manage paid campaigns to reach qualified prospects and measure the outcomes that genuinely matter to the business.",
      problem: "Campaign activity is not supported by a clear target, creative direction, journey, or measurement plan.",
      fit: "Businesses ready to connect paid reach with a clear offer, audience, and conversion path.",
      covers: ["Campaign planning", "Audience direction", "Creative coordination", "Performance optimization"],
      outcome: "More informed paid-media decisions focused on qualified business actions.",
      cta: "Discuss Paid Media",
    },
  ],
  ar: [
    {
      id: "management",
      title: "إدارة حسابات السوشيال ميديا",
      preview: "من التخطيط والنشر إلى المتابعة وتحليل الأداء، بندير حساباتك وفق استراتيجية واضحة مرتبطة بأهداف البيزنس.",
      problem: "الحساب شغال، لكن القرارات اليومية منفصلة وصعب تستمر بنفس الجودة.",
      fit: "البيزنس اللي محتاج إدارة مستمرة وقرارات مرتبطة بالأولويات الأكبر.",
      covers: ["التخطيط والنشر", "متابعة الحساب", "توجيه المجتمع", "مراجعة الأداء"],
      outcome: "نظام إدارة أوضح وأكثر استمرارية وارتباطًا بالبيزنس.",
      cta: "ناقش إدارة حسابك",
    },
    {
      id: "strategy",
      title: "استراتيجية المحتوى",
      preview: "بنحوّل أهداف البيزنس وأفكاره إلى اتجاه محتوى واضح يحدد الرسائل، الجمهور، أعمدة المحتوى ودور كل قطعة في رحلة العميل.",
      problem: "المحتوى عشوائي أو متكرر أو بعيد عن الجمهور ورحلة العميل.",
      fit: "البراندات اللي عندها أفكار وخبرة لكنها محتاجة اتجاه منظم قبل إنتاج محتوى أكتر.",
      covers: ["الجمهور وتحديد المكانة", "الرسائل", "أعمدة المحتوى", "دور المحتوى في رحلة العميل"],
      outcome: "اتجاه محتوى هادف يوجّه القرارات والإنتاج.",
      cta: "ابنِ اتجاه المحتوى",
    },
    {
      id: "audit",
      title: "تحليل حسابات السوشيال ميديا",
      preview: "بنراجع حساباتك والمحتوى والأداء علشان نحدد نقاط الضعف، الفرص وأهم الخطوات المطلوبة للتحسين.",
      problem: "شايف النشاط والبيانات، لكن أسباب ضعف الأداء لسه مش واضحة.",
      fit: "البيزنس اللي محتاج نقطة بداية مدروسة قبل تغيير الاستراتيجية أو الإدارة.",
      covers: ["الملف التعريفي والمكانة", "اتجاه المحتوى", "مؤشرات الأداء", "أولويات التحسين"],
      outcome: "رؤية أوضح للوضع الحالي والخطوات التالية الأكثر صلة.",
      cta: "اطلب تحليل حسابك",
    },
    {
      id: "paid-media",
      title: "إدارة الإعلانات المدفوعة",
      preview: "بنخطط وندير الحملات الإعلانية بهدف الوصول لعملاء محتملين مؤهلين وقياس النتائج التي تهم البيزنس فعلًا.",
      problem: "نشاط الحملات مش مدعوم بهدف أو كرياتيف أو رحلة أو طريقة قياس واضحة.",
      fit: "البيزنس الجاهز يربط الوصول المدفوع بعرض وجمهور ومسار تحويل واضح.",
      covers: ["تخطيط الحملات", "توجيه الجمهور", "تنسيق الكرياتيف", "تحسين الأداء"],
      outcome: "قرارات إعلانية أذكى تركز على الإجراءات المؤهلة للبيزنس.",
      cta: "ناقش الإعلانات المدفوعة",
    },
  ],
} as const;

export const audiences = {
  en: [
    {
      title: "Growing Businesses & Founders",
      copy: "If you run an established business but social media is not producing a clear impact—or you are still managing everything yourself—we help build a clearer system for content, management, and performance.",
      challenges: "Limited time, scattered decisions, and unclear business impact.",
      relevant: "Management, content strategy, and account audit.",
      improve: "Consistency, decision-making, and focus across the account.",
    },
    {
      title: "E-commerce Brands",
      copy: "If your ads generate traffic but conversions remain weak, we review the content, creative, customer journey, and performance instead of assuming the problem is only the advertising.",
      challenges: "Traffic without enough action and a fragmented customer journey.",
      relevant: "Content strategy, paid media, and performance audit.",
      improve: "Alignment between message, creative, journey, and measurement.",
    },
    {
      title: "Personal Brands & Experts",
      copy: "If you have strong expertise but your account does not communicate it clearly, we help turn that expertise into structured content that builds trust, authority, and action.",
      challenges: "Valuable expertise without a clear or consistent content structure.",
      relevant: "Positioning, content strategy, and account management.",
      improve: "Clarity, trust, and a stronger path from expertise to action.",
    },
    {
      title: "Local Businesses",
      copy: "If your business depends on nearby customers, we build a content direction that helps people discover the brand, engage with it, and understand its value.",
      challenges: "Low local awareness and an unclear reason to choose the brand.",
      relevant: "Content strategy, management, and paid media.",
      improve: "Local discovery, brand understanding, and meaningful engagement.",
    },
  ],
  ar: [
    {
      title: "البيزنس المتنامي والمؤسسون",
      copy: "لو عندك بيزنس قائم لكن السوشيال ميديا مش بتجيب نتيجة واضحة، أو بتدير الحساب بنفسك ومش لاقي وقت، هنساعدك نبني نظام أوضح لإدارة المحتوى والأداء.",
      challenges: "وقت محدود وقرارات مشتتة وتأثير غير واضح على البيزنس.",
      relevant: "الإدارة واستراتيجية المحتوى وتحليل الحساب.",
      improve: "الاستمرارية وجودة القرار والتركيز داخل الحساب.",
    },
    {
      title: "براندات التجارة الإلكترونية",
      copy: "لو الإعلانات بتجيب زيارات لكن التحويلات ضعيفة، بنراجع المحتوى والكرياتيف ورحلة العميل والأداء بدل ما نفترض إن المشكلة في الإعلان وحده.",
      challenges: "زيارات بدون إجراء كافٍ ورحلة عميل غير مترابطة.",
      relevant: "استراتيجية المحتوى والإعلانات المدفوعة وتحليل الأداء.",
      improve: "الترابط بين الرسالة والكرياتيف والرحلة والقياس.",
    },
    {
      title: "البراندات الشخصية والخبراء",
      copy: "لو عندك خبرة قوية لكن حسابك مش بيعكسها، بنساعدك تحول خبرتك إلى محتوى منظم يبني الثقة والسلطة ويقرب الجمهور من اتخاذ خطوة.",
      challenges: "خبرة قوية من غير هيكل محتوى واضح ومستمر.",
      relevant: "تحديد المكانة واستراتيجية المحتوى وإدارة الحساب.",
      improve: "الوضوح والثقة ومسار أقوى من الخبرة إلى اتخاذ خطوة.",
    },
    {
      title: "الأنشطة المحلية",
      copy: "لو نشاطك بيعتمد على العملاء القريبين منك، بنبني اتجاه محتوى يساعد الناس تعرف البراند، تتفاعل معاه وتفهم القيمة اللي بيقدمها.",
      challenges: "وعي محلي محدود وسبب غير واضح لاختيار البراند.",
      relevant: "استراتيجية المحتوى والإدارة والإعلانات المدفوعة.",
      improve: "الاكتشاف المحلي وفهم البراند والتفاعل الهادف.",
    },
  ],
} as const;

export const caseStudies = [
  { slug: "abq-al-hayah", name: { en: "Abq Al Hayah", ar: "عبق الحياة" }, category: { en: "Social media strategy", ar: "استراتيجية السوشيال ميديا" }, coverImage: null, logo: null, summary: null, challenge: null, strategy: null, execution: null, results: null, gallery: [], videos: [], testimonial: null, serviceTags: ["Strategy", "Content", "Management"], featured: true, published: false },
  { slug: "kham-al-jamal", name: { en: "Kham Al Jamal", ar: "خام الجمال" }, category: { en: "Brand content", ar: "محتوى البراند" }, coverImage: null, logo: null, summary: null, challenge: null, strategy: null, execution: null, results: null, gallery: [], videos: [], testimonial: null, serviceTags: ["Content", "Management"], featured: false, published: false },
  { slug: "lina", name: { en: "Lina", ar: "لينا" }, category: { en: "Personal brand", ar: "براند شخصي" }, coverImage: null, logo: null, summary: null, challenge: null, strategy: null, execution: null, results: null, gallery: [], videos: [], testimonial: null, serviceTags: ["Strategy", "Content"], featured: false, published: false },
] as const;

export const auditAreas = [
  { id: "profile", en: "Profile clarity", ar: "وضوح الملف التعريفي" },
  { id: "audience", en: "Audience and positioning", ar: "الجمهور وتحديد المكانة" },
  { id: "direction", en: "Content direction", ar: "اتجاه المحتوى" },
  { id: "consistency", en: "Content consistency", ar: "استمرارية المحتوى" },
  { id: "creative", en: "Creative quality", ar: "جودة المحتوى الإبداعي" },
  { id: "engagement", en: "Engagement patterns", ar: "أنماط التفاعل" },
  { id: "performance", en: "Performance indicators", ar: "مؤشرات الأداء" },
  { id: "journey", en: "Customer journey", ar: "رحلة العميل" },
  { id: "conversion", en: "Conversion opportunities", ar: "فرص التحويل" },
  { id: "priorities", en: "Improvement priorities", ar: "أولويات التحسين" },
] as const;

export const processSteps = {
  en: [["01", "Understand", "We clarify the business, audience, objectives, and current challenge."], ["02", "Strategize", "We define the direction, priorities, channels, and role of content."], ["03", "Create", "We turn the strategy into purposeful content and practical execution."], ["04", "Measure", "We review the indicators connected to the agreed business objective."], ["05", "Optimize", "We use what we learn to refine the next decisions and actions."]],
  ar: [["01", "نفهم", "بنحدد طبيعة البيزنس والجمهور والأهداف والتحدي الحالي."], ["02", "نخطط", "بنحدد الاتجاه والأولويات والقنوات ودور المحتوى."], ["03", "ننفذ", "بنحوّل الاستراتيجية إلى محتوى هادف وتنفيذ عملي."], ["04", "نقيس", "بنراجع المؤشرات المرتبطة بهدف البيزنس المتفق عليه."], ["05", "نحسن", "بنستخدم اللي اتعلمناه علشان نطوّر القرارات والخطوات الجاية."]],
} as const;

const faqItems = {
  en: [
    ["Do you work with every type of business?", "We first review the business, audience, and challenge to confirm whether the collaboration is a suitable fit."],
    ["Does the service include content creation?", "Content requirements depend on the selected service and scope. We clarify what is included during the consultation."],
    ["Do you manage paid advertising?", "Yes, paid media management is available when the business has a clear objective, offer, and suitable starting point."],
    ["Can we start with one service?", "Yes. We can begin with the most relevant priority and define any additional needs later."],
    ["Is there a monthly contract?", "The working format depends on the service and scope. We discuss the suitable arrangement before starting."],
    ["How do you measure social media success?", "We agree on indicators connected to the business objective instead of relying only on visible platform metrics."],
    ["I am not sure which service I need. Where should I start?", "Start with a consultation or account audit so we can understand the current situation and define the priority."],
  ],
  ar: [
    ["هل بتشتغلوا مع كل أنواع البيزنس؟", "بنراجع طبيعة البيزنس والجمهور والتحدي الأول علشان نتأكد إن التعاون مناسب."],
    ["هل الخدمة تشمل صناعة المحتوى؟", "احتياجات المحتوى بتختلف حسب الخدمة ونطاق العمل، وبنوضح بالتحديد إيه المشمول خلال الاستشارة."],
    ["هل بتقدموا إدارة للإعلانات المدفوعة؟", "نعم، إدارة الإعلانات متاحة لما يكون للبيزنس هدف وعرض ونقطة بداية واضحة."],
    ["هل أقدر أبدأ بخدمة واحدة؟", "نعم، ممكن نبدأ بالأولوية الأكثر صلة ونحدد أي احتياجات إضافية بعد كده."],
    ["هل فيه تعاقد شهري؟", "شكل العمل بيتحدد حسب الخدمة ونطاقها، وبنناقش الترتيب المناسب قبل البداية."],
    ["إزاي بنقيس نجاح السوشيال ميديا؟", "بنتفق على مؤشرات مرتبطة بهدف البيزنس بدل الاعتماد على الأرقام الظاهرة على المنصة فقط."],
    ["مش عارف الخدمة المناسبة، أبدأ منين؟", "ابدأ باستشارة أو تحليل للحساب علشان نفهم الوضع الحالي ونحدد الأولوية."],
  ],
} as const;

export const copy = {
  en: {
    languageLabel: "العربية",
    menu: "Menu",
    book: "Book a Consultation",
    common: { eyebrow: "Habiba Dapour", learn: "Learn more", caseSoon: "Case study details coming soon", featured: "Featured Case Study", processTitle: "Understand. Strategize. Create. Measure. Optimize.", processIntro: "Our work does not begin with a posting calendar. We start by understanding the business, then build, execute, measure, and improve.", whatsappMessage: "Hi Habiba, I would like to book a social media consultation." },
    footer: { heading: "Ready for a clearer social media direction?", copy: "Start with a conversation about your business, challenge, and priorities.", contact: "Contact", location: "Marsa Matrouh, Egypt · Available worldwide", explore: "Explore" },
    home: {
      eyebrow: "Strategic social media for growing businesses",
      title: "We turn social media from an online presence into a real channel for business growth.",
      intro: "From understanding your business goals and building the strategy to content, account management, performance analysis, and paid media, every step is connected to a clear objective.",
      work: "Explore Our Work",
      imageAlt: "Habiba Dapour, social media account manager",
      problemTitle: "Your social media is active—but is it actually helping the business?",
      problems: ["You publish consistently but generate few leads.", "You have followers but limited business impact.", "Your content lacks a clear strategy.", "Your ads bring traffic without enough conversions.", "You are managing everything yourself instead of focusing on the business."],
      problemClose: "If any of these challenges sound familiar, we can identify what is holding the account back and define a clearer way forward.",
      aboutTitle: "Strategy before posting. Business impact before vanity metrics.",
      aboutCopy: "At Habiba Dapour, we start by understanding the business, audience, and objectives before deciding what to publish. We combine strategy, content, management, and performance analysis so social media becomes a meaningful part of business growth.",
      aboutCta: "Learn More About Our Approach",
      servicesTitle: "Services Built Around Business Needs",
      helpTitle: "Who We Help",
      casesTitle: "Selected Case Studies",
      casesIntro: "Explore the thinking and work behind each project, from understanding the challenge and building the strategy to execution and improvement.",
      casesCta: "Explore All Case Studies",
      pathwaysTitle: "Find the right place to start",
      pathways: [["About", "See the principles and process behind our work.", "/about"], ["Services", "Explore management, strategy, audits, and paid media.", "/services"], ["Who We Help", "Find the approach that matches your business challenge.", "/who-we-help"], ["Case Studies", "Explore selected projects and our way of thinking.", "/case-studies"], ["Social Media Audit", "Identify weaknesses, opportunities, and improvement priorities.", "/social-media-audit"], ["Book a Consultation", "Tell us about the business and define the next step.", "/contact"]],
      finalTitle: "Not sure whether your account needs management, a strategy, or an audit?",
      finalCopy: "Start with a consultation so we can understand the challenge and identify the right next step.",
    },
    services: { eyebrow: "Services", title: "We do not deliver isolated posts. We build a system around your business goals.", intro: "Every service starts with the current business situation and connects strategy, execution, and measurement to a clear objective.", labels: ["The customer problem", "Best suited for", "What it covers", "Intended business outcome"], decisionTitle: "Not sure which service to start with?", decisionCopy: "We can begin with an account audit or a consultation to understand the current situation and define the priorities." },
    help: { eyebrow: "Who We Help", title: "Different Businesses. Different Challenges. The Right Approach.", intro: "The right social media system depends on how the business grows, sells, and builds trust.", labels: ["Common challenges", "Relevant services", "What collaboration can improve"] },
    cases: { eyebrow: "Our Work", title: "Case Studies", intro: "We do not present isolated designs or posts. Each project will show the challenge, strategic thinking, execution, and the content developed around it." },
    about: { eyebrow: "About", title: "A Growth Partner, Not Just Account Management.", body: "At Habiba Dapour, we treat social media as part of business growth—not as a posting schedule. We understand the business, audience, and goals before building the right strategy, content direction, and measurement approach.", imageAlt: "Habiba Dapour", valuesTitle: "The principles behind the work", values: [["Strategy First", "Every step begins with understanding the business goals—not choosing the appearance of a post."], ["Creativity with Purpose", "We develop ideas suited to the brand and audience while serving a clear purpose."], ["Data & Transparency", "We review performance openly and make decisions using actual data."], ["Partnership & Progress", "We approach every project as an ongoing partnership focused on learning, improvement, and growth."]] },
    faq: { title: "Frequently Asked Questions", items: faqItems.en },
    contact: { eyebrow: "Contact", title: "Let’s Understand Your Business.", intro: "Share a few details about your business and current challenge. We will review them to identify the most suitable starting point before getting in touch.", labels: ["Name", "Business name", "Email", "Phone number", "Country", "Business type", "Instagram or website URL", "Main current challenge", "Service of interest", "Monthly marketing budget", "Preferred contact method", "Additional details"], challenges: ["Content strategy", "Account management", "Paid advertising", "Performance and conversions", "Generating leads", "Not sure yet"], serviceOptions: ["Social Media Management", "Content Strategy", "Social Media Audit", "Paid Media Management", "Consultation", "Not sure yet"], methods: ["WhatsApp", "Email", "Phone call"], select: "Select an option", submit: "Book a Consultation", success: "We have received your details. We will review the challenge and contact you to define the right next step.", successNote: "Your prepared request has opened in WhatsApp. Send it to complete your request." },
    audit: { eyebrow: "Social Media Audit", title: "Not Sure What Is Holding Your Account Back?", intro: "Through a structured account audit, we review your current content and performance to identify weaknesses, opportunities, and the most important improvement actions.", areasTitle: "What the audit can review", formTitle: "Request your account audit", formIntro: "Tell us about the account and choose the areas you want us to review.", sections: ["About you and the business", "About the account", "Areas to review"], labels: ["Name", "Business name", "Email", "Phone number", "Country", "Primary platform", "Account URL", "Main business goal", "Main current challenge", "Additional context"], consent: "I confirm these details are accurate and agree to be contacted about this request.", platforms: ["Instagram", "Facebook", "TikTok", "LinkedIn", "Multiple platforms"], help: "Choose all relevant areas.", submit: "Request an Account Audit", success: "We have received your audit details. We will review the account context and contact you about the next appropriate step.", actions: ["Send by email", "Print request", "Edit details"] },
  },
  ar: {
    languageLabel: "English",
    menu: "القائمة",
    book: "احجز استشارتك",
    common: { eyebrow: "Habiba Dapour", learn: "اعرف أكتر", caseSoon: "تفاصيل دراسة الحالة قريبًا", featured: "دراسة حالة مميزة", processTitle: "نفهم. نخطط. ننفذ. نقيس. نحسن.", processIntro: "شغلنا مش بيبدأ بجدول بوستات. بنبدأ بفهم البيزنس، وبعدها نبني وننفذ ونقيس ونطور.", whatsappMessage: "مرحبًا Habiba، أرغب في حجز استشارة للسوشيال ميديا." },
    footer: { heading: "جاهز لاتجاه أوضح على السوشيال ميديا؟", copy: "ابدأ بمحادثة عن البيزنس والتحدي والأولويات.", contact: "تواصل معنا", location: "مرسى مطروح، مصر · متاحون للعمل مع العملاء في أي مكان", explore: "استكشف" },
    home: {
      eyebrow: "سوشيال ميديا استراتيجية للبيزنس الطموح",
      title: "نحوّل السوشيال ميديا من مجرد حضور إلى قناة حقيقية لنمو البيزنس.",
      intro: "من فهم أهداف البيزنس وبناء الاستراتيجية، إلى صناعة المحتوى، إدارة الحسابات، تحليل الأداء والإعلانات المدفوعة؛ كل خطوة عندنا مرتبطة بهدف واضح وقرار مدروس.",
      work: "شوف سابقة أعمالنا",
      imageAlt: "Habiba Dapour، مديرة حسابات سوشيال ميديا",
      problemTitle: "السوشيال ميديا عندك شغالة… بس هل بتخدم البيزنس؟",
      problems: ["بتنشر باستمرار لكن مفيش عملاء محتملين؟", "عندك متابعين لكن تأثيرهم على المبيعات ضعيف؟", "المحتوى عشوائي ومفيش استراتيجية واضحة؟", "الإعلانات بتجيب زيارات من غير تحويلات كفاية؟", "بتدير كل حاجة بنفسك ومش لاقي وقت للبيزنس؟"],
      problemClose: "لو واحدة من المشاكل دي بتحصل معاك، نقدر نحدد السبب ونبني نقطة بداية أوضح.",
      aboutTitle: "استراتيجية قبل النشر، ونتائج قبل الأرقام الشكلية.",
      aboutCopy: "في Habiba Dapour، بنبدأ بفهم البيزنس والجمهور والأهداف قبل ما نقرر هننشر إيه. بنجمع بين الاستراتيجية، المحتوى، الإدارة وتحليل الأداء علشان السوشيال ميديا تكون جزءًا حقيقيًا من رحلة نمو البيزنس.",
      aboutCta: "اعرف أكتر عن طريقتنا",
      servicesTitle: "خدمات تبدأ من احتياج البيزنس",
      helpTitle: "مين نقدر نساعد؟",
      casesTitle: "سابقة أعمالنا",
      casesIntro: "هنا بنعرض طريقة التفكير والعمل وراء كل مشروع، من فهم التحدي ووضع الاستراتيجية إلى التنفيذ والتطوير.",
      casesCta: "شوف كل المشاريع",
      pathwaysTitle: "اختار نقطة البداية المناسبة",
      pathways: [["عن Habiba Dapour", "اتعرف على المبادئ وطريقة العمل اللي بنعتمد عليها.", "/about"], ["الخدمات", "استكشف الإدارة والاستراتيجية والتحليل والإعلانات المدفوعة.", "/services"], ["مين نقدر نساعد", "شوف النهج المناسب لنوع البيزنس والتحدي اللي بتواجهه.", "/who-we-help"], ["سابقة الأعمال", "استكشف مشروعات مختارة وطريقة تفكيرنا فيها.", "/case-studies"], ["تحليل السوشيال ميديا", "حدد نقاط الضعف والفرص وأولويات التحسين.", "/social-media-audit"], ["احجز استشارتك", "شاركنا تفاصيل البيزنس وحدد الخطوة الجاية.", "/contact"]],
      finalTitle: "مش عارف حسابك محتاج إدارة، استراتيجية ولا تحليل؟",
      finalCopy: "ابدأ باستشارة نحدد فيها التحدي وأنسب خطوة للبيزنس.",
    },
    services: { eyebrow: "الخدمات", title: "مش بنقدم بوستات منفصلة؛ بنبني منظومة تخدم هدف البيزنس.", intro: "كل خدمة بتبدأ من وضع البيزنس الحالي وبتربط الاستراتيجية والتنفيذ والقياس بهدف واضح.", labels: ["مشكلة العميل", "مناسبة لمين", "الخدمة تشمل", "النتيجة المستهدفة للبيزنس"], decisionTitle: "مش متأكد تبدأ بأنهي خدمة؟", decisionCopy: "ممكن نبدأ بتحليل للحساب أو استشارة نفهم من خلالها الوضع الحالي ونحدد الأولويات." },
    help: { eyebrow: "مين نقدر نساعد", title: "حلول مختلفة حسب نوع البيزنس والتحدي", intro: "نظام السوشيال ميديا المناسب بيتغير حسب طريقة نمو البيزنس وبيعه وبنائه للثقة.", labels: ["تحديات شائعة", "الخدمات المناسبة", "إيه اللي ممكن نطوره"] },
    cases: { eyebrow: "أعمالنا", title: "سابقة الأعمال", intro: "مش بنعرض تصاميم أو بوستات منفصلة وبس. كل مشروع هنا هيعرض التحدي، طريقة التفكير، الاستراتيجية، التنفيذ والمحتوى الذي تم تطويره." },
    about: { eyebrow: "عن Habiba Dapour", title: "شريك نمو، مش مجرد إدارة حسابات.", body: "في Habiba Dapour، بنتعامل مع السوشيال ميديا كجزء من نمو البيزنس، مش كجدول نشر. بنفهم طبيعة المشروع والجمهور والأهداف، وبعدها نبني الاستراتيجية والمحتوى وطريقة القياس المناسبة.", imageAlt: "Habiba Dapour", valuesTitle: "المبادئ اللي بتحرك شغلنا", values: [["الاستراتيجية أولًا", "كل خطوة بتبدأ من فهم أهداف البيزنس، مش من اختيار شكل البوست."], ["إبداع له هدف", "بنطور أفكار تناسب طبيعة البراند والجمهور وتخدم رسالة واضحة."], ["البيانات والوضوح", "بنراجع الأداء بوضوح وناخد قراراتنا بناءً على البيانات الفعلية."], ["الشراكة والتطوير", "بنتعامل مع كل مشروع كشراكة مستمرة هدفها التعلم والتحسين والنمو."]] },
    faq: { title: "أسئلة شائعة", items: faqItems.ar },
    contact: { eyebrow: "تواصل معنا", title: "خلينا نعرف أكتر عن البيزنس.", intro: "شاركنا معلومات بسيطة عن مشروعك والتحدي الحالي، وهنراجعها علشان نحدد أنسب نقطة بداية قبل التواصل معاك.", labels: ["الاسم", "اسم البيزنس", "البريد الإلكتروني", "رقم الهاتف", "الدولة", "نوع البيزنس", "رابط الحساب أو الموقع", "أكبر تحدٍ حالي", "الخدمة المطلوبة", "الميزانية التسويقية الشهرية", "وسيلة التواصل المفضلة", "تفاصيل إضافية"], challenges: ["استراتيجية المحتوى", "إدارة الحساب", "الإعلانات المدفوعة", "الأداء والتحويلات", "توليد عملاء محتملين", "مش متأكد لسه"], serviceOptions: ["إدارة حسابات السوشيال ميديا", "استراتيجية المحتوى", "تحليل السوشيال ميديا", "إدارة الإعلانات المدفوعة", "استشارة", "مش متأكد لسه"], methods: ["واتساب", "البريد الإلكتروني", "مكالمة هاتفية"], select: "اختر من القائمة", submit: "احجز استشارتك", success: "تم استلام بياناتك. هنراجع التحدي ونتواصل معاك لتحديد الخطوة المناسبة.", successNote: "تم فتح طلبك المجهز في واتساب. أرسله لإكمال الطلب." },
    audit: { eyebrow: "تحليل السوشيال ميديا", title: "مش عارف إيه اللي موقف نمو حسابك؟", intro: "من خلال تحليل الحساب، بنراجع الوضع الحالي للمحتوى والأداء ونحدد أهم نقاط الضعف والفرص والخطوات المطلوبة للتحسين.", areasTitle: "إيه اللي ممكن نراجعه؟", formTitle: "اطلب تحليل حسابك", formIntro: "شاركنا معلومات الحساب وحدد الجوانب اللي محتاج نراجعها.", sections: ["عنك وعن البيزنس", "عن الحساب", "جوانب التحليل"], labels: ["الاسم", "اسم البيزنس", "البريد الإلكتروني", "رقم الهاتف", "الدولة", "المنصة الأساسية", "رابط الحساب", "هدف البيزنس الأساسي", "أكبر تحدٍ حالي", "تفاصيل إضافية"], consent: "أؤكد أن البيانات صحيحة وأوافق على التواصل معي بخصوص هذا الطلب.", platforms: ["إنستجرام", "فيسبوك", "تيك توك", "لينكدإن", "أكثر من منصة"], help: "اختر كل الجوانب المناسبة.", submit: "اطلب تحليل حسابك", success: "تم استلام بيانات التحليل. هنراجع سياق الحساب ونتواصل معاك بخصوص الخطوة المناسبة.", actions: ["أرسل بالبريد", "اطبع الطلب", "عدل البيانات"] },
  },
} as const;
